version: '3.8'
services:
  # MongoDB сервис
  mongodb:
    image: mongo:latest
    container_name: notemind-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=notemind
    ports:
      - "27017:27017"
    networks:
      - notemind-network

  # Redis сервис (для кэширования и веб-сокетов)
  redis:
    image: redis:alpine
    container_name: notemind-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - notemind-network

  # Серверная часть приложения
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: notemind-server
    restart: unless-stopped
    volumes:
      - ./server:/app:delegated
      - /app/node_modules
      - uploads:/app/uploads    # Исправлено имя тома
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_URI=mongodb://mongodb:27017/notemind  # Исправлен URI для Docker
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRE=${JWT_EXPIRE:-30d}
      - REDIS_HOST=redis       # Исправлен хост для Docker
      - REDIS_PORT=6379
      - SOCKET_CORS_ORIGIN=${SOCKET_CORS_ORIGIN:-http://localhost:3000}
    networks:
      - notemind-network

  # Клиентская часть приложения
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: notemind-client
    restart: unless-stopped
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - notemind-network

# Определение томов
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local

# Определение сети
networks:
  notemind-network:
    driver: bridge