FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Создаем директории с правильными правами
RUN mkdir -p uploads && chmod 755 uploads
RUN mkdir -p logs && chmod 755 logs

# Устанавливаем правильного владельца
RUN chown -R node:node /app

# Переключаемся на непривилегированного пользователя
USER node

EXPOSE 5000

CMD ["npm", "start"]
